---
title: RVHSRobotics
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: Competiting in the BEST competition
email: redbankvalleyrobotics@gmail.com
description: Learn why we are the best team in Pennsylvania.
baseurl: "/forty-jekyll-theme"
url: ''
author: theMattGreen
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: "(716) 555-5555"
tiles-source: pages
tiles-count: 6
facebook_url: https://facebook.com/rvhsrobotics
github_url: https://github.com/rvhsrobotics
instagram_url: https://instagram.com/rvhsrobotics
twitter_url: https://twitter.com/rvhsrobotics
markdown: kramdown
sass:
  style: compressed
